### ISSUE TITLE
How to send error message using trackjs?

### ISSUE THREAD

**Issue by beretboat** [mikelambert/react-native-trackjs#1]
So after

``` js
import trackjs from 'react-native-trackjs';
trackjs.init({token: myTrackJsToken});
```

Then what? How to use trackjs function?
I tried `trackjs.track('...');` but then I see "...not a fucntion" error.

Sorry for this silly question. I'm new to javascript.

**Comment by mikelambert** [comment]
That should be all that's required. It will install a JavaScript exception handler with react native to process exceptions and report them up to the trackjs server.

It will only work when you build your app in release mode, so as not to pollute the server with your debug exceptions.

It worked when I last tested it, though my recently release brand new react native app has zero JS exceptions across a few hundred sessions, which has me suspicious that something has broken in my exception reporting with tracks (or elsewhere) in my released client base.

**Comment by beretboat** [comment]
Ah, release mode, that's why. Thank you!
